### PR TITLE
fix mobile popup display

### LINKED ISSUE #225: update pop-up/hover
- right now, the names (text) of certain species appear off center in the pop up (see screenshots)

- on the site, there's more padding around the text than there is in the design

- for **mobile**: should the pop up remain visible/activated until a user selects another tree?

|alignment examples|
|---|
|IMG_6259|
|IMG_6260|
|Image from iOS|

|zeplin (designed) pop up on hover|
|---|
|Screen Shot 2019-09-23 at 10 34 54 PM|

(see #216)

### PR DESCRIPTION
**Pull request by mrtmrt233**
resolves #225

# Screenshots
| before | after |
|Screen Shot 2020-04-23 at 12 13 46 AM|
Screen Shot 2020-04-23 at 12 11 13 AM
|

# What I did
this problem is caused by the default minWidth setting of Leaflet popUp. Overriding the default setting to 0 fixes the problem.

### CODE REVIEW

File: public/js/Map.js [hunk 1]
```diff
@@ -139,7 +139,7 @@ var app = this.app || {};
       }
 
       marker.tree = tree;
-      marker.bindPopup(tree.name_common, {closeButton: false, offset:[0,-2]}); //offset moves popup up
+      marker.bindPopup(tree.name_common, {closeButton: false, minWidth:0});
```
Comment (emillipede) [inline public/js/Map.js:142]: thank you for solving this problem @mrtmrt233! 

the offset in the existing map.js creates a small gap between the marker and the bottom point of the hover. the gap is visible in your first screenshot. can you please add back the offset? 

thank you again!!!
